-- ---------------------------------------------------------------------------
-- Green Light — inbound screening verdicts + the AI company profile cache.
--
-- Two unrelated-looking columns sets that come from the same round of work on
-- the §5 intake pipeline and the §6 negotiation workspace.
--
-- 1. inbound_emails.subject / spam_score / spam_reasons
--
--    Until now the screener only ever *flagged* a delivery
--    (deal_chats.is_likely_sponsorship, migration 0017): the deal room was
--    created either way, which meant every newsletter that reached a creator's
--    alias still spent an AI evaluation, a WHOIS lookup and a WhatsApp alert.
--    The screener can now refuse a delivery outright, and a refusal never
--    creates a deal room or stores the body.
--
--    That makes the refusal itself the only record, so it has to be a usable
--    one — `detail` alone cannot answer "which real offer did your filter
--    eat?". The subject is stored (bounded, and only ever the subject line, a
--    header rather than the offer body — the body is still never written here,
--    per this table's own comment from 0008) alongside the numeric score and
--    the rules that fired, so a false positive is diagnosable and the rubric
--    is tunable against real traffic rather than guesswork.
--
-- 2. deal_chats.company_profile
--
--    The Company & Domain Intelligence panel's AI half: a written background
--    and trading history for the sender's domain plus a trustworthiness score,
--    generated on demand by src/lib/ai/company-intel.ts and cached here so a
--    creator reopening the room does not spend a second model call.
--
--    Distinct from security_check on purpose. security_check is *measured* —
--    WHOIS records and a Safe Browsing verdict, facts with a source. This is
--    *generated* — a language model's account of a company, which can be
--    confidently wrong. Keeping them in separate columns keeps the UI able to
--    say which is which, which is the same "never present something as
--    verified unless it is" rule §7.2 applies to audience data.
--
-- Same trust rule as ai_evaluation / offered_amount / security_check
-- (0003_rls_policies.sql, 0017): table-level UPDATE on deal_chats was revoked
-- from `authenticated` in 0003 and company_profile is named in no column-level
-- GRANT since, so it is service_role-only by default. A creator cannot write
-- the platform's finding about the party they are negotiating with.
-- ---------------------------------------------------------------------------

alter table public.inbound_emails
  add column if not exists subject text,
  add column if not exists spam_score integer,
  add column if not exists spam_reasons text[];

comment on column public.inbound_emails.subject is
  'Subject line of the delivery, truncated. Stored so a screener refusal is reviewable — a rejected delivery has no deal room and no stored message, so this row is the only trace. Still never the offer body.';
comment on column public.inbound_emails.spam_score is
  'src/lib/ai/spam-filter.ts screen score, 0-100. Higher = more likely a real sponsorship offer. Null for deliveries that failed before screening (no alias, no body, banned account).';
comment on column public.inbound_emails.spam_reasons is
  'The screener rules that actually fired, in plain language, so a false positive is diagnosable without re-running the message.';

alter table public.deal_chats
  add column if not exists company_profile jsonb;

comment on column public.deal_chats.company_profile is
  'Cached src/lib/ai/company-intel.ts result (background, history, trustworthinessScore, signals, confidence, generatedAt) for an external sender. GENERATED by a language model, unlike security_check which is MEASURED from WHOIS/Safe Browsing — the UI must keep the two visually distinct. service_role-written only; never granted to authenticated.';

-- Reviewing what the screener refused is an admin workflow ("did we eat a real
-- offer?"), and inbound_emails_status_idx (0008) already orders by created_at
-- within a status, which is exactly that query.
